version: '2.4'
volumes:
  pgdatachallenge:
services:
  app:
    build:
      context: .
      target: dev
    depends_on:
      database:
        condition: service_healthy
    environment:
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - ./:/app
  database:
    image: postgres:12.3
    restart: on-failure
    healthcheck:
      test: pg_isready -h 127.0.0.1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - pgdatachallenge:/var/lib/postgresql/data
